baseURL: https://dathinaios.github.io
languageCode: en-uk
title: Dionysis Athinaios
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true
customCSS: "/main.css"
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Dionysis Athinaios
  description: "Code | Sound | Music"
  keywords: [Blog, Portfolio, PaperMod]
  author: Dionysis Athinaios
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  # assets:
  #   favicon: "<link / abs url>"
  #   favicon16x16: "<link / abs url>"
  #   favicon32x32: "<link / abs url>"
  #   apple_touch_icon: "<link / abs url>"
  #   safari_pinned_tab: "<link / abs url>"

  label:
    text: "Dionysis Athinaios"
    # icon: images/logo.jpeg
    # iconHeight: 35

  profileMode:
      enabled: true
      title: "Dionysis Athinaios" # optional default will be site title
      subtitle: "Code | Sound | Music"
      imageUrl: "images/logo.jpeg" # optional
      imageTitle: "dathinaios" # optional
      imageWidth: 240 # custom size
      imageHeight: 240 # custom size
      buttons:
        - name: Projects
          url: "/projects"
        # - name: Articles
        #   url: "/posts"

  homeInfoParams:
    Title: "\\> welcome"
    Content: I am a musician / sound designer / software developer. I have worked extensively with the [SuperCollider](http://supercollider.sourceforge.net) audio programming language which was the main tool during my PhD research. I have since used a variety of technologies, currently focusing on software development for audio applications and the creation of tools for artists working with sound in unconventional ways. I am the director of the UK-based Music & Audio company [FasmaTwist](https://www.fasmatwist.com).

  socialIcons:
    - name: github
      url: "https://github.com/dathinaios"
    - name: email
      url: "https://dathin.netlify.app"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    # - identifier: posts
    #   name: Posts
    #   url: /posts/
    #   weight: 20
    - identifier: github
      name: "GitHub"
      url: https://github.com/dathinaios
      weight: 30

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
